# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settings_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='settings_service.proto',
  package='settings',
  syntax='proto3',
  serialized_pb=_b('\n\x16settings_service.proto\x12\x08settings\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17google/rpc/status.proto\"J\n\x11ListConfigRequest\x12\x0e\n\x06parent\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\t\x12\x12\n\npage_token\x18\x03 \x01(\t\"P\n\x12ListConfigResponse\x12!\n\x07\x63onfigs\x18\x01 \x03(\x0b\x32\x10.settings.Config\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\"\xa6\x01\n\x19ListConfigByGroupResponse\x12?\n\x06\x63onfig\x18\x01 \x03(\x0b\x32/.settings.ListConfigByGroupResponse.ConfigEntry\x1aH\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.settings.ConfigByNameMap:\x02\x38\x01\"\xad\x01\n\x0f\x43onfigByNameMap\x12\x35\n\x06\x63onfig\x18\x01 \x03(\x0b\x32%.settings.ConfigByNameMap.ConfigEntry\x12\"\n\x06status\x18\x02 \x01(\x0b\x32\x12.google.rpc.Status\x1a?\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.settings.Config:\x02\x38\x01\"X\n\x06\x43onfig\x12\r\n\x05group\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\"\n\x06status\x18\x04 \x01(\x0b\x32\x12.google.rpc.Status\"/\n\x10GetConfigRequest\x12\r\n\x05group\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x12\n\x10SetConfigRequest2\xfd\x02\n\x0fSettingsService\x12I\n\nListConfig\x12\x1b.settings.ListConfigRequest\x1a\x1c.settings.ListConfigResponse\"\x00\x12\x34\n\x0c\x43reateConfig\x12\x10.settings.Config\x1a\x10.settings.Config\"\x00\x12\x37\n\x0fGetConfigByName\x12\x10.settings.Config\x1a\x10.settings.Config\"\x00\x12\x41\n\x10GetConfigByGroup\x12\x10.settings.Config\x1a\x19.settings.ConfigByNameMap\"\x00\x12\x31\n\tSetConfig\x12\x10.settings.Config\x1a\x10.settings.Config\"\x00\x12:\n\x0c\x44\x65leteConfig\x12\x10.settings.Config\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_rpc_dot_status__pb2.DESCRIPTOR,])




_LISTCONFIGREQUEST = _descriptor.Descriptor(
  name='ListConfigRequest',
  full_name='settings.ListConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='settings.ListConfigRequest.parent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='settings.ListConfigRequest.page_size', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_token', full_name='settings.ListConfigRequest.page_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=164,
)


_LISTCONFIGRESPONSE = _descriptor.Descriptor(
  name='ListConfigResponse',
  full_name='settings.ListConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='configs', full_name='settings.ListConfigResponse.configs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_page_token', full_name='settings.ListConfigResponse.next_page_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=246,
)


_LISTCONFIGBYGROUPRESPONSE_CONFIGENTRY = _descriptor.Descriptor(
  name='ConfigEntry',
  full_name='settings.ListConfigByGroupResponse.ConfigEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='settings.ListConfigByGroupResponse.ConfigEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='settings.ListConfigByGroupResponse.ConfigEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=415,
)

_LISTCONFIGBYGROUPRESPONSE = _descriptor.Descriptor(
  name='ListConfigByGroupResponse',
  full_name='settings.ListConfigByGroupResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='settings.ListConfigByGroupResponse.config', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LISTCONFIGBYGROUPRESPONSE_CONFIGENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=415,
)


_CONFIGBYNAMEMAP_CONFIGENTRY = _descriptor.Descriptor(
  name='ConfigEntry',
  full_name='settings.ConfigByNameMap.ConfigEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='settings.ConfigByNameMap.ConfigEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='settings.ConfigByNameMap.ConfigEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=528,
  serialized_end=591,
)

_CONFIGBYNAMEMAP = _descriptor.Descriptor(
  name='ConfigByNameMap',
  full_name='settings.ConfigByNameMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='settings.ConfigByNameMap.config', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='settings.ConfigByNameMap.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONFIGBYNAMEMAP_CONFIGENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=591,
)


_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='settings.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='settings.Config.group', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='settings.Config.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='settings.Config.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='settings.Config.status', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=681,
)


_GETCONFIGREQUEST = _descriptor.Descriptor(
  name='GetConfigRequest',
  full_name='settings.GetConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='settings.GetConfigRequest.group', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='settings.GetConfigRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=683,
  serialized_end=730,
)


_SETCONFIGREQUEST = _descriptor.Descriptor(
  name='SetConfigRequest',
  full_name='settings.SetConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=732,
  serialized_end=750,
)

_LISTCONFIGRESPONSE.fields_by_name['configs'].message_type = _CONFIG
_LISTCONFIGBYGROUPRESPONSE_CONFIGENTRY.fields_by_name['value'].message_type = _CONFIGBYNAMEMAP
_LISTCONFIGBYGROUPRESPONSE_CONFIGENTRY.containing_type = _LISTCONFIGBYGROUPRESPONSE
_LISTCONFIGBYGROUPRESPONSE.fields_by_name['config'].message_type = _LISTCONFIGBYGROUPRESPONSE_CONFIGENTRY
_CONFIGBYNAMEMAP_CONFIGENTRY.fields_by_name['value'].message_type = _CONFIG
_CONFIGBYNAMEMAP_CONFIGENTRY.containing_type = _CONFIGBYNAMEMAP
_CONFIGBYNAMEMAP.fields_by_name['config'].message_type = _CONFIGBYNAMEMAP_CONFIGENTRY
_CONFIGBYNAMEMAP.fields_by_name['status'].message_type = google_dot_rpc_dot_status__pb2._STATUS
_CONFIG.fields_by_name['status'].message_type = google_dot_rpc_dot_status__pb2._STATUS
DESCRIPTOR.message_types_by_name['ListConfigRequest'] = _LISTCONFIGREQUEST
DESCRIPTOR.message_types_by_name['ListConfigResponse'] = _LISTCONFIGRESPONSE
DESCRIPTOR.message_types_by_name['ListConfigByGroupResponse'] = _LISTCONFIGBYGROUPRESPONSE
DESCRIPTOR.message_types_by_name['ConfigByNameMap'] = _CONFIGBYNAMEMAP
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
DESCRIPTOR.message_types_by_name['GetConfigRequest'] = _GETCONFIGREQUEST
DESCRIPTOR.message_types_by_name['SetConfigRequest'] = _SETCONFIGREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListConfigRequest = _reflection.GeneratedProtocolMessageType('ListConfigRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTCONFIGREQUEST,
  __module__ = 'settings_service_pb2'
  # @@protoc_insertion_point(class_scope:settings.ListConfigRequest)
  ))
_sym_db.RegisterMessage(ListConfigRequest)

ListConfigResponse = _reflection.GeneratedProtocolMessageType('ListConfigResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTCONFIGRESPONSE,
  __module__ = 'settings_service_pb2'
  # @@protoc_insertion_point(class_scope:settings.ListConfigResponse)
  ))
_sym_db.RegisterMessage(ListConfigResponse)

ListConfigByGroupResponse = _reflection.GeneratedProtocolMessageType('ListConfigByGroupResponse', (_message.Message,), dict(

  ConfigEntry = _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), dict(
    DESCRIPTOR = _LISTCONFIGBYGROUPRESPONSE_CONFIGENTRY,
    __module__ = 'settings_service_pb2'
    # @@protoc_insertion_point(class_scope:settings.ListConfigByGroupResponse.ConfigEntry)
    ))
  ,
  DESCRIPTOR = _LISTCONFIGBYGROUPRESPONSE,
  __module__ = 'settings_service_pb2'
  # @@protoc_insertion_point(class_scope:settings.ListConfigByGroupResponse)
  ))
_sym_db.RegisterMessage(ListConfigByGroupResponse)
_sym_db.RegisterMessage(ListConfigByGroupResponse.ConfigEntry)

ConfigByNameMap = _reflection.GeneratedProtocolMessageType('ConfigByNameMap', (_message.Message,), dict(

  ConfigEntry = _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), dict(
    DESCRIPTOR = _CONFIGBYNAMEMAP_CONFIGENTRY,
    __module__ = 'settings_service_pb2'
    # @@protoc_insertion_point(class_scope:settings.ConfigByNameMap.ConfigEntry)
    ))
  ,
  DESCRIPTOR = _CONFIGBYNAMEMAP,
  __module__ = 'settings_service_pb2'
  # @@protoc_insertion_point(class_scope:settings.ConfigByNameMap)
  ))
_sym_db.RegisterMessage(ConfigByNameMap)
_sym_db.RegisterMessage(ConfigByNameMap.ConfigEntry)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
  DESCRIPTOR = _CONFIG,
  __module__ = 'settings_service_pb2'
  # @@protoc_insertion_point(class_scope:settings.Config)
  ))
_sym_db.RegisterMessage(Config)

GetConfigRequest = _reflection.GeneratedProtocolMessageType('GetConfigRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCONFIGREQUEST,
  __module__ = 'settings_service_pb2'
  # @@protoc_insertion_point(class_scope:settings.GetConfigRequest)
  ))
_sym_db.RegisterMessage(GetConfigRequest)

SetConfigRequest = _reflection.GeneratedProtocolMessageType('SetConfigRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETCONFIGREQUEST,
  __module__ = 'settings_service_pb2'
  # @@protoc_insertion_point(class_scope:settings.SetConfigRequest)
  ))
_sym_db.RegisterMessage(SetConfigRequest)


_LISTCONFIGBYGROUPRESPONSE_CONFIGENTRY.has_options = True
_LISTCONFIGBYGROUPRESPONSE_CONFIGENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_CONFIGBYNAMEMAP_CONFIGENTRY.has_options = True
_CONFIGBYNAMEMAP_CONFIGENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_SETTINGSSERVICE = _descriptor.ServiceDescriptor(
  name='SettingsService',
  full_name='settings.SettingsService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=753,
  serialized_end=1134,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListConfig',
    full_name='settings.SettingsService.ListConfig',
    index=0,
    containing_service=None,
    input_type=_LISTCONFIGREQUEST,
    output_type=_LISTCONFIGRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateConfig',
    full_name='settings.SettingsService.CreateConfig',
    index=1,
    containing_service=None,
    input_type=_CONFIG,
    output_type=_CONFIG,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetConfigByName',
    full_name='settings.SettingsService.GetConfigByName',
    index=2,
    containing_service=None,
    input_type=_CONFIG,
    output_type=_CONFIG,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetConfigByGroup',
    full_name='settings.SettingsService.GetConfigByGroup',
    index=3,
    containing_service=None,
    input_type=_CONFIG,
    output_type=_CONFIGBYNAMEMAP,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetConfig',
    full_name='settings.SettingsService.SetConfig',
    index=4,
    containing_service=None,
    input_type=_CONFIG,
    output_type=_CONFIG,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteConfig',
    full_name='settings.SettingsService.DeleteConfig',
    index=5,
    containing_service=None,
    input_type=_CONFIG,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SETTINGSSERVICE)

DESCRIPTOR.services_by_name['SettingsService'] = _SETTINGSSERVICE

# @@protoc_insertion_point(module_scope)
