# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import settings_service_pb2 as settings__service__pb2


class SettingsServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListConfig = channel.unary_unary(
        '/settings.SettingsService/ListConfig',
        request_serializer=settings__service__pb2.ListConfigRequest.SerializeToString,
        response_deserializer=settings__service__pb2.ListConfigResponse.FromString,
        )
    self.CreateConfig = channel.unary_unary(
        '/settings.SettingsService/CreateConfig',
        request_serializer=settings__service__pb2.Config.SerializeToString,
        response_deserializer=settings__service__pb2.Config.FromString,
        )
    self.GetConfigByName = channel.unary_unary(
        '/settings.SettingsService/GetConfigByName',
        request_serializer=settings__service__pb2.Config.SerializeToString,
        response_deserializer=settings__service__pb2.Config.FromString,
        )
    self.GetConfigByGroup = channel.unary_unary(
        '/settings.SettingsService/GetConfigByGroup',
        request_serializer=settings__service__pb2.Config.SerializeToString,
        response_deserializer=settings__service__pb2.ConfigByNameMap.FromString,
        )
    self.SetConfig = channel.unary_unary(
        '/settings.SettingsService/SetConfig',
        request_serializer=settings__service__pb2.Config.SerializeToString,
        response_deserializer=settings__service__pb2.Config.FromString,
        )
    self.DeleteConfig = channel.unary_unary(
        '/settings.SettingsService/DeleteConfig',
        request_serializer=settings__service__pb2.Config.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class SettingsServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetConfigByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetConfigByGroup(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SettingsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListConfig': grpc.unary_unary_rpc_method_handler(
          servicer.ListConfig,
          request_deserializer=settings__service__pb2.ListConfigRequest.FromString,
          response_serializer=settings__service__pb2.ListConfigResponse.SerializeToString,
      ),
      'CreateConfig': grpc.unary_unary_rpc_method_handler(
          servicer.CreateConfig,
          request_deserializer=settings__service__pb2.Config.FromString,
          response_serializer=settings__service__pb2.Config.SerializeToString,
      ),
      'GetConfigByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetConfigByName,
          request_deserializer=settings__service__pb2.Config.FromString,
          response_serializer=settings__service__pb2.Config.SerializeToString,
      ),
      'GetConfigByGroup': grpc.unary_unary_rpc_method_handler(
          servicer.GetConfigByGroup,
          request_deserializer=settings__service__pb2.Config.FromString,
          response_serializer=settings__service__pb2.ConfigByNameMap.SerializeToString,
      ),
      'SetConfig': grpc.unary_unary_rpc_method_handler(
          servicer.SetConfig,
          request_deserializer=settings__service__pb2.Config.FromString,
          response_serializer=settings__service__pb2.Config.SerializeToString,
      ),
      'DeleteConfig': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteConfig,
          request_deserializer=settings__service__pb2.Config.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'settings.SettingsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
